# Generated by Django 4.2.7 on 2023-11-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDbApi', '0002_alter_account_calories_alter_account_carbs_and_more'),
        ('FoodDbApi', '0002_alter_account_daily_streak_alter_account_last_reset'),
    ]

    operations = [
    ]
