# Generated by Django 4.2.7 on 2023-11-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDbApi', '0004_alter_account_calories_alter_account_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionmodel',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
